service: pufouniversity
 
provider:
  name: aws
  runtime: nodejs8.10
  region: ${opt:region, self:custom.defaultRegion}
  stage: dev${env:SLSUSER, ""}

custom:
  defaultRegion: eu-west-1
  stage: ${opt:stage, self:provider.stage}
 
functions:
  initialTest:
    handler: src/functions/getMasters.handler
    events:
      - http:
          path: api/getMasters/{name}
          method: get

resources:
  Resources:
    MastersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.mastersTable}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST